// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Customer    *customer
	Order       *order
	OrderDetail *orderDetail
	Product     *product
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Customer = &Q.Customer
	Order = &Q.Order
	OrderDetail = &Q.OrderDetail
	Product = &Q.Product
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Customer:    newCustomer(db, opts...),
		Order:       newOrder(db, opts...),
		OrderDetail: newOrderDetail(db, opts...),
		Product:     newProduct(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Customer    customer
	Order       order
	OrderDetail orderDetail
	Product     product
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Customer:    q.Customer.clone(db),
		Order:       q.Order.clone(db),
		OrderDetail: q.OrderDetail.clone(db),
		Product:     q.Product.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Customer:    q.Customer.replaceDB(db),
		Order:       q.Order.replaceDB(db),
		OrderDetail: q.OrderDetail.replaceDB(db),
		Product:     q.Product.replaceDB(db),
	}
}

type queryCtx struct {
	Customer    ICustomerDo
	Order       IOrderDo
	OrderDetail IOrderDetailDo
	Product     IProductDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Customer:    q.Customer.WithContext(ctx),
		Order:       q.Order.WithContext(ctx),
		OrderDetail: q.OrderDetail.WithContext(ctx),
		Product:     q.Product.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
